# Generated by Django 3.1 on 2020-09-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200909_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='count',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.student'),
        ),
    ]
