# Generated by Django 3.1 on 2020-09-13 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200913_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended_classes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_classes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
