# Generated by Django 3.1 on 2020-09-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200914_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='percentage',
        ),
    ]
