# Generated by Django 3.1 on 2020-09-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200915_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
    ]
