# Generated by Django 3.1 on 2020-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200919_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student_performance',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
