# Generated by Django 3.1 on 2020-09-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200919_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_performance',
        ),
    ]
