# Generated by Django 3.1 on 2020-09-18 22:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200919_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student_performance',
            field=models.CharField(default=main.models.Marks.something, max_length=100),
        ),
    ]
